// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v3.21.12
// source: proto/ax.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State represents the state of an execution
type State int32

const (
	State_STATE_UNSPECIFIED State = 0 // Unspecified state
	State_STATE_PENDING     State = 1
	State_STATE_FAILED      State = 2
	State_STATE_COMPLETED   State = 3
	State_STATE_CANCELED    State = 4
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_PENDING",
		2: "STATE_FAILED",
		3: "STATE_COMPLETED",
		4: "STATE_CANCELED",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_PENDING":     1,
		"STATE_FAILED":      2,
		"STATE_COMPLETED":   3,
		"STATE_CANCELED":    4,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ax_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_proto_ax_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{0}
}

// CancelReason explains why an in-flight execution is canceled.
type CancelReason int32

const (
	CancelReason_CANCEL_REASON_UNSPECIFIED    CancelReason = 0
	CancelReason_CANCEL_REASON_USER_REQUESTED CancelReason = 1
	CancelReason_CANCEL_REASON_TIMEOUT        CancelReason = 2
	CancelReason_CANCEL_REASON_INTERNAL_ERROR CancelReason = 3
)

// Enum value maps for CancelReason.
var (
	CancelReason_name = map[int32]string{
		0: "CANCEL_REASON_UNSPECIFIED",
		1: "CANCEL_REASON_USER_REQUESTED",
		2: "CANCEL_REASON_TIMEOUT",
		3: "CANCEL_REASON_INTERNAL_ERROR",
	}
	CancelReason_value = map[string]int32{
		"CANCEL_REASON_UNSPECIFIED":    0,
		"CANCEL_REASON_USER_REQUESTED": 1,
		"CANCEL_REASON_TIMEOUT":        2,
		"CANCEL_REASON_INTERNAL_ERROR": 3,
	}
)

func (x CancelReason) Enum() *CancelReason {
	p := new(CancelReason)
	*p = x
	return p
}

func (x CancelReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CancelReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ax_proto_enumTypes[1].Descriptor()
}

func (CancelReason) Type() protoreflect.EnumType {
	return &file_proto_ax_proto_enumTypes[1]
}

func (x CancelReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CancelReason.Descriptor instead.
func (CancelReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{1}
}

// A conversation is the historical session that consist of
// a number of execution. A conversation cannot be continued
// before the last execution is completed or failed.
type StepEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	InteractionId  string                 `protobuf:"bytes,2,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	AgentId        string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentConfig    *structpb.Struct       `protobuf:"bytes,4,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"`
	Steps          []*Step                `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	State          State                  `protobuf:"varint,6,opt,name=state,proto3,enum=ax.State" json:"state,omitempty"`
	// session_id is an opaque, caller-assigned key grouping events across
	// potentially many conversation_ids.
	SessionId     string `protobuf:"bytes,8,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepEvent) Reset() {
	*x = StepEvent{}
	mi := &file_proto_ax_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepEvent) ProtoMessage() {}

func (x *StepEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepEvent.ProtoReflect.Descriptor instead.
func (*StepEvent) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{0}
}

func (x *StepEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *StepEvent) GetInteractionId() string {
	if x != nil {
		return x.InteractionId
	}
	return ""
}

func (x *StepEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StepEvent) GetAgentConfig() *structpb.Struct {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

func (x *StepEvent) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *StepEvent) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *StepEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type HarnessStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Per-execution agent configuration.
	AgentConfig   []byte  `protobuf:"bytes,1,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"`
	Steps         []*Step `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessStart) Reset() {
	*x = HarnessStart{}
	mi := &file_proto_ax_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessStart) ProtoMessage() {}

func (x *HarnessStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessStart.ProtoReflect.Descriptor instead.
func (*HarnessStart) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{1}
}

func (x *HarnessStart) GetAgentConfig() []byte {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

func (x *HarnessStart) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

// HarnessCancel aborts the in-flight harness execution.
type HarnessCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        CancelReason           `protobuf:"varint,1,opt,name=reason,proto3,enum=ax.CancelReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessCancel) Reset() {
	*x = HarnessCancel{}
	mi := &file_proto_ax_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessCancel) ProtoMessage() {}

func (x *HarnessCancel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessCancel.ProtoReflect.Descriptor instead.
func (*HarnessCancel) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{2}
}

func (x *HarnessCancel) GetReason() CancelReason {
	if x != nil {
		return x.Reason
	}
	return CancelReason_CANCEL_REASON_UNSPECIFIED
}

type HarnessRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	AgentId        string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*HarnessRequest_Start
	//	*HarnessRequest_Cancel
	Type          isHarnessRequest_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessRequest) Reset() {
	*x = HarnessRequest{}
	mi := &file_proto_ax_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessRequest) ProtoMessage() {}

func (x *HarnessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessRequest.ProtoReflect.Descriptor instead.
func (*HarnessRequest) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{3}
}

func (x *HarnessRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *HarnessRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HarnessRequest) GetType() isHarnessRequest_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *HarnessRequest) GetStart() *HarnessStart {
	if x != nil {
		if x, ok := x.Type.(*HarnessRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *HarnessRequest) GetCancel() *HarnessCancel {
	if x != nil {
		if x, ok := x.Type.(*HarnessRequest_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isHarnessRequest_Type interface {
	isHarnessRequest_Type()
}

type HarnessRequest_Start struct {
	Start *HarnessStart `protobuf:"bytes,3,opt,name=start,proto3,oneof"`
}

type HarnessRequest_Cancel struct {
	Cancel *HarnessCancel `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"`
}

func (*HarnessRequest_Start) isHarnessRequest_Type() {}

func (*HarnessRequest_Cancel) isHarnessRequest_Type() {}

type HarnessOutputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []*Step                `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessOutputs) Reset() {
	*x = HarnessOutputs{}
	mi := &file_proto_ax_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessOutputs) ProtoMessage() {}

func (x *HarnessOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessOutputs.ProtoReflect.Descriptor instead.
func (*HarnessOutputs) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{4}
}

func (x *HarnessOutputs) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A status code, corresponds to google.golang.org/grpc/codes.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// A description of the error.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_ax_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type HarnessEnd struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Terminal state for the harness execution.
	State State `protobuf:"varint,1,opt,name=state,proto3,enum=ax.State" json:"state,omitempty"`
	// Optional error details.
	Error         *Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessEnd) Reset() {
	*x = HarnessEnd{}
	mi := &file_proto_ax_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessEnd) ProtoMessage() {}

func (x *HarnessEnd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessEnd.ProtoReflect.Descriptor instead.
func (*HarnessEnd) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{6}
}

func (x *HarnessEnd) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *HarnessEnd) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type HarnessResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*HarnessResponse_Outputs
	//	*HarnessResponse_End
	Type          isHarnessResponse_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessResponse) Reset() {
	*x = HarnessResponse{}
	mi := &file_proto_ax_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessResponse) ProtoMessage() {}

func (x *HarnessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessResponse.ProtoReflect.Descriptor instead.
func (*HarnessResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{7}
}

func (x *HarnessResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *HarnessResponse) GetType() isHarnessResponse_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *HarnessResponse) GetOutputs() *HarnessOutputs {
	if x != nil {
		if x, ok := x.Type.(*HarnessResponse_Outputs); ok {
			return x.Outputs
		}
	}
	return nil
}

func (x *HarnessResponse) GetEnd() *HarnessEnd {
	if x != nil {
		if x, ok := x.Type.(*HarnessResponse_End); ok {
			return x.End
		}
	}
	return nil
}

type isHarnessResponse_Type interface {
	isHarnessResponse_Type()
}

type HarnessResponse_Outputs struct {
	Outputs *HarnessOutputs `protobuf:"bytes,2,opt,name=outputs,proto3,oneof"`
}

type HarnessResponse_End struct {
	End *HarnessEnd `protobuf:"bytes,3,opt,name=end,proto3,oneof"`
}

func (*HarnessResponse_Outputs) isHarnessResponse_Type() {}

func (*HarnessResponse_End) isHarnessResponse_Type() {}

// CreateInteractionEvent for creating an interaction.
type CreateInteractionEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // Unique conversation identifier
	Inputs         []*Step                `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`                                       // New inputs
	AgentId        string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                      // Agent ID, empty selects the default agent
	AgentConfig    []byte                 `protobuf:"bytes,5,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"`          // Per-request agent configuration (opaque JSON), if any
	// session_id is forwarded verbatim onto the StepEvent(s) this call logs.
	SessionId     string `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInteractionEvent) Reset() {
	*x = CreateInteractionEvent{}
	mi := &file_proto_ax_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInteractionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInteractionEvent) ProtoMessage() {}

func (x *CreateInteractionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInteractionEvent.ProtoReflect.Descriptor instead.
func (*CreateInteractionEvent) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{8}
}

func (x *CreateInteractionEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *CreateInteractionEvent) GetInputs() []*Step {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *CreateInteractionEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateInteractionEvent) GetAgentConfig() []byte {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

func (x *CreateInteractionEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// CreateInteractionResponse contains the result of an interaction.
type CreateInteractionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       []*Step                `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"` // Output content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInteractionResponse) Reset() {
	*x = CreateInteractionResponse{}
	mi := &file_proto_ax_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInteractionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInteractionResponse) ProtoMessage() {}

func (x *CreateInteractionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInteractionResponse.ProtoReflect.Descriptor instead.
func (*CreateInteractionResponse) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{9}
}

func (x *CreateInteractionResponse) GetOutputs() []*Step {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type Step struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Description string                 `protobuf:"bytes,16,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*Step_Content
	//	*Step_Thought
	//	*Step_ToolCall
	//	*Step_ToolResult
	Type          isStep_Type `protobuf_oneof:"type"`
	Index         int64       `protobuf:"varint,22,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_proto_ax_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{10}
}

func (x *Step) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Step) GetType() isStep_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Step) GetContent() *ContentStep {
	if x != nil {
		if x, ok := x.Type.(*Step_Content); ok {
			return x.Content
		}
	}
	return nil
}

func (x *Step) GetThought() *ThoughtStep {
	if x != nil {
		if x, ok := x.Type.(*Step_Thought); ok {
			return x.Thought
		}
	}
	return nil
}

func (x *Step) GetToolCall() *ToolCallStep {
	if x != nil {
		if x, ok := x.Type.(*Step_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *Step) GetToolResult() *ToolResultStep {
	if x != nil {
		if x, ok := x.Type.(*Step_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *Step) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type isStep_Type interface {
	isStep_Type()
}

type Step_Content struct {
	Content *ContentStep `protobuf:"bytes,12,opt,name=content,proto3,oneof"`
}

type Step_Thought struct {
	Thought *ThoughtStep `protobuf:"bytes,3,opt,name=thought,proto3,oneof"`
}

type Step_ToolCall struct {
	ToolCall *ToolCallStep `protobuf:"bytes,4,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type Step_ToolResult struct {
	ToolResult *ToolResultStep `protobuf:"bytes,5,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

func (*Step_Content) isStep_Type() {}

func (*Step_Thought) isStep_Type() {}

func (*Step_ToolCall) isStep_Type() {}

func (*Step_ToolResult) isStep_Type() {}

type ContentStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       []*Content             `protobuf:"bytes,2,rep,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentStep) Reset() {
	*x = ContentStep{}
	mi := &file_proto_ax_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentStep) ProtoMessage() {}

func (x *ContentStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentStep.ProtoReflect.Descriptor instead.
func (*ContentStep) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{11}
}

func (x *ContentStep) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ContentStep) GetContent() []*Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type ThoughtStep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A signature hash for backend validation.
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// A summary of the thought.
	Summary       []*Content `protobuf:"bytes,2,rep,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThoughtStep) Reset() {
	*x = ThoughtStep{}
	mi := &file_proto_ax_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThoughtStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThoughtStep) ProtoMessage() {}

func (x *ThoughtStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThoughtStep.ProtoReflect.Descriptor instead.
func (*ThoughtStep) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{12}
}

func (x *ThoughtStep) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ThoughtStep) GetSummary() []*Content {
	if x != nil {
		return x.Summary
	}
	return nil
}

type ToolCallStep struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Signature []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*ToolCallStep_FunctionCall
	Type          isToolCallStep_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallStep) Reset() {
	*x = ToolCallStep{}
	mi := &file_proto_ax_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallStep) ProtoMessage() {}

func (x *ToolCallStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallStep.ProtoReflect.Descriptor instead.
func (*ToolCallStep) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{13}
}

func (x *ToolCallStep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCallStep) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ToolCallStep) GetType() isToolCallStep_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ToolCallStep) GetFunctionCall() *FunctionCallStep {
	if x != nil {
		if x, ok := x.Type.(*ToolCallStep_FunctionCall); ok {
			return x.FunctionCall
		}
	}
	return nil
}

type isToolCallStep_Type interface {
	isToolCallStep_Type()
}

type ToolCallStep_FunctionCall struct {
	FunctionCall *FunctionCallStep `protobuf:"bytes,3,opt,name=function_call,json=functionCall,proto3,oneof"`
}

func (*ToolCallStep_FunctionCall) isToolCallStep_Type() {}

type FunctionCallStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     *structpb.Struct       `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionCallStep) Reset() {
	*x = FunctionCallStep{}
	mi := &file_proto_ax_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCallStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCallStep) ProtoMessage() {}

func (x *FunctionCallStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCallStep.ProtoReflect.Descriptor instead.
func (*FunctionCallStep) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{14}
}

func (x *FunctionCallStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionCallStep) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type ToolResultStep struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CallId    string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Signature []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*ToolResultStep_FunctionResult
	Type          isToolResultStep_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResultStep) Reset() {
	*x = ToolResultStep{}
	mi := &file_proto_ax_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultStep) ProtoMessage() {}

func (x *ToolResultStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResultStep.ProtoReflect.Descriptor instead.
func (*ToolResultStep) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{15}
}

func (x *ToolResultStep) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolResultStep) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ToolResultStep) GetType() isToolResultStep_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ToolResultStep) GetFunctionResult() *FunctionResultStep {
	if x != nil {
		if x, ok := x.Type.(*ToolResultStep_FunctionResult); ok {
			return x.FunctionResult
		}
	}
	return nil
}

type isToolResultStep_Type interface {
	isToolResultStep_Type()
}

type ToolResultStep_FunctionResult struct {
	FunctionResult *FunctionResultStep `protobuf:"bytes,3,opt,name=function_result,json=functionResult,proto3,oneof"`
}

func (*ToolResultStep_FunctionResult) isToolResultStep_Type() {}

type FunctionResultStep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the tool that was called.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Whether the tool call resulted in an error.
	IsError bool `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	// The result of the tool call.
	Result        *Value `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionResultStep) Reset() {
	*x = FunctionResultStep{}
	mi := &file_proto_ax_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionResultStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionResultStep) ProtoMessage() {}

func (x *FunctionResultStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionResultStep.ProtoReflect.Descriptor instead.
func (*FunctionResultStep) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{16}
}

func (x *FunctionResultStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionResultStep) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *FunctionResultStep) GetResult() *Value {
	if x != nil {
		return x.Result
	}
	return nil
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The kind of value.
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_NullValue
	//	*Value_NumberValue
	//	*Value_StringValue
	//	*Value_BoolValue
	//	*Value_StructValue
	//	*Value_ListValue
	//	*Value_ContentValue
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_proto_ax_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{17}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetNullValue() structpb.NullValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_NullValue); ok {
			return x.NullValue
		}
	}
	return structpb.NullValue(0)
}

func (x *Value) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetStructValue() *structpb.Struct {
	if x != nil {
		if x, ok := x.Kind.(*Value_StructValue); ok {
			return x.StructValue
		}
	}
	return nil
}

func (x *Value) GetListValue() *ListValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

func (x *Value) GetContentValue() *Content {
	if x != nil {
		if x, ok := x.Kind.(*Value_ContentValue); ok {
			return x.ContentValue
		}
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_NullValue struct {
	// Represents a null value.
	NullValue structpb.NullValue `protobuf:"varint,1,opt,name=null_value,json=nullValue,proto3,enum=google.protobuf.NullValue,oneof"`
}

type Value_NumberValue struct {
	// Represents a double value.
	NumberValue float64 `protobuf:"fixed64,2,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type Value_StringValue struct {
	// Represents a string value.
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_BoolValue struct {
	// Represents a boolean value.
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_StructValue struct {
	// Represents a structured value.
	StructValue *structpb.Struct `protobuf:"bytes,5,opt,name=struct_value,json=structValue,proto3,oneof"`
}

type Value_ListValue struct {
	// Represents a repeated `Value`.
	ListValue *ListValue `protobuf:"bytes,6,opt,name=list_value,json=listValue,proto3,oneof"`
}

type Value_ContentValue struct {
	// Represents rich content (text, image, etc.).
	ContentValue *Content `protobuf:"bytes,7,opt,name=content_value,json=contentValue,proto3,oneof"`
}

func (*Value_NullValue) isValue_Kind() {}

func (*Value_NumberValue) isValue_Kind() {}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_BoolValue) isValue_Kind() {}

func (*Value_StructValue) isValue_Kind() {}

func (*Value_ListValue) isValue_Kind() {}

func (*Value_ContentValue) isValue_Kind() {}

// `ListValue` is a wrapper around a repeated field of values.
type ListValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Repeated field of dynamically typed values.
	Values        []*Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_proto_ax_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ax_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_proto_ax_proto_rawDescGZIP(), []int{18}
}

func (x *ListValue) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_proto_ax_proto protoreflect.FileDescriptor

const file_proto_ax_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ax.proto\x12\x02ax\x1a\x1cgoogle/protobuf/struct.proto\x1a\x13proto/content.proto\"\x92\x02\n" +
	"\tStepEvent\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12%\n" +
	"\x0einteraction_id\x18\x02 \x01(\tR\rinteractionId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12:\n" +
	"\fagent_config\x18\x04 \x01(\v2\x17.google.protobuf.StructR\vagentConfig\x12\x1e\n" +
	"\x05steps\x18\x05 \x03(\v2\b.ax.StepR\x05steps\x12\x1f\n" +
	"\x05state\x18\x06 \x01(\x0e2\t.ax.StateR\x05state\x12\x1d\n" +
	"\n" +
	"session_id\x18\b \x01(\tR\tsessionId\"Q\n" +
	"\fHarnessStart\x12!\n" +
	"\fagent_config\x18\x01 \x01(\fR\vagentConfig\x12\x1e\n" +
	"\x05steps\x18\x02 \x03(\v2\b.ax.StepR\x05steps\"9\n" +
	"\rHarnessCancel\x12(\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x10.ax.CancelReasonR\x06reason\"\xb3\x01\n" +
	"\x0eHarnessRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12(\n" +
	"\x05start\x18\x03 \x01(\v2\x10.ax.HarnessStartH\x00R\x05start\x12+\n" +
	"\x06cancel\x18\x04 \x01(\v2\x11.ax.HarnessCancelH\x00R\x06cancelB\x06\n" +
	"\x04type\"0\n" +
	"\x0eHarnessOutputs\x12\x1e\n" +
	"\x05steps\x18\x01 \x03(\v2\b.ax.StepR\x05steps\"=\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"N\n" +
	"\n" +
	"HarnessEnd\x12\x1f\n" +
	"\x05state\x18\x01 \x01(\x0e2\t.ax.StateR\x05state\x12\x1f\n" +
	"\x05error\x18\x02 \x01(\v2\t.ax.ErrorR\x05error\"\x96\x01\n" +
	"\x0fHarnessResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12.\n" +
	"\aoutputs\x18\x02 \x01(\v2\x12.ax.HarnessOutputsH\x00R\aoutputs\x12\"\n" +
	"\x03end\x18\x03 \x01(\v2\x0e.ax.HarnessEndH\x00R\x03endB\x06\n" +
	"\x04type\"\xc6\x01\n" +
	"\x16CreateInteractionEvent\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12 \n" +
	"\x06inputs\x18\x02 \x03(\v2\b.ax.StepR\x06inputs\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12!\n" +
	"\fagent_config\x18\x05 \x01(\fR\vagentConfig\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionIdJ\x04\b\x03\x10\x04\"?\n" +
	"\x19CreateInteractionResponse\x12\"\n" +
	"\aoutputs\x18\x01 \x03(\v2\b.ax.StepR\aoutputs\"\x88\x02\n" +
	"\x04Step\x12 \n" +
	"\vdescription\x18\x10 \x01(\tR\vdescription\x12+\n" +
	"\acontent\x18\f \x01(\v2\x0f.ax.ContentStepH\x00R\acontent\x12+\n" +
	"\athought\x18\x03 \x01(\v2\x0f.ax.ThoughtStepH\x00R\athought\x12/\n" +
	"\ttool_call\x18\x04 \x01(\v2\x10.ax.ToolCallStepH\x00R\btoolCall\x125\n" +
	"\vtool_result\x18\x05 \x01(\v2\x12.ax.ToolResultStepH\x00R\n" +
	"toolResult\x12\x14\n" +
	"\x05index\x18\x16 \x01(\x03R\x05indexB\x06\n" +
	"\x04type\"Z\n" +
	"\vContentStep\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12%\n" +
	"\acontent\x18\x02 \x03(\v2\v.ax.ContentR\acontentR\x04typeR\n" +
	"event_type\"d\n" +
	"\vThoughtStep\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12%\n" +
	"\asummary\x18\x02 \x03(\v2\v.ax.ContentR\asummaryR\x04typeR\n" +
	"event_type\"\x8d\x01\n" +
	"\fToolCallStep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12;\n" +
	"\rfunction_call\x18\x03 \x01(\v2\x14.ax.FunctionCallStepH\x00R\ffunctionCallB\x06\n" +
	"\x04typeR\n" +
	"event_type\"c\n" +
	"\x10FunctionCallStep\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\targuments\x18\x02 \x01(\v2\x17.google.protobuf.StructR\targumentsR\x04type\"\x9e\x01\n" +
	"\x0eToolResultStep\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12A\n" +
	"\x0ffunction_result\x18\x03 \x01(\v2\x16.ax.FunctionResultStepH\x00R\x0efunctionResultB\x06\n" +
	"\x04typeR\n" +
	"event_type\"\x8a\x01\n" +
	"\x12FunctionResultStep\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\x12!\n" +
	"\x06result\x18\a \x01(\v2\t.ax.ValueR\x06resultJ\x04\b\x01\x10\x02J\x04\b\x04\x10\x05J\x04\b\n" +
	"\x10\vJ\x04\b\v\x10\fJ\x04\b\f\x10\rR\x04type\"\xd9\x02\n" +
	"\x05Value\x12;\n" +
	"\n" +
	"null_value\x18\x01 \x01(\x0e2\x1a.google.protobuf.NullValueH\x00R\tnullValue\x12#\n" +
	"\fnumber_value\x18\x02 \x01(\x01H\x00R\vnumberValue\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12<\n" +
	"\fstruct_value\x18\x05 \x01(\v2\x17.google.protobuf.StructH\x00R\vstructValue\x12.\n" +
	"\n" +
	"list_value\x18\x06 \x01(\v2\r.ax.ListValueH\x00R\tlistValue\x122\n" +
	"\rcontent_value\x18\a \x01(\v2\v.ax.ContentH\x00R\fcontentValueB\x06\n" +
	"\x04kind\".\n" +
	"\tListValue\x12!\n" +
	"\x06values\x18\x01 \x03(\v2\t.ax.ValueR\x06values*l\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_PENDING\x10\x01\x12\x10\n" +
	"\fSTATE_FAILED\x10\x02\x12\x13\n" +
	"\x0fSTATE_COMPLETED\x10\x03\x12\x12\n" +
	"\x0eSTATE_CANCELED\x10\x04*\x8c\x01\n" +
	"\fCancelReason\x12\x1d\n" +
	"\x19CANCEL_REASON_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCANCEL_REASON_USER_REQUESTED\x10\x01\x12\x19\n" +
	"\x15CANCEL_REASON_TIMEOUT\x10\x02\x12 \n" +
	"\x1cCANCEL_REASON_INTERNAL_ERROR\x10\x032H\n" +
	"\x0eHarnessService\x126\n" +
	"\aConnect\x12\x12.ax.HarnessRequest\x1a\x13.ax.HarnessResponse(\x010\x012g\n" +
	"\x13InteractionsService\x12P\n" +
	"\x11CreateInteraction\x12\x1a.ax.CreateInteractionEvent\x1a\x1d.ax.CreateInteractionResponse0\x01B$Z\"github.com/ktock/checkpointd/protob\x06proto3"

var (
	file_proto_ax_proto_rawDescOnce sync.Once
	file_proto_ax_proto_rawDescData []byte
)

func file_proto_ax_proto_rawDescGZIP() []byte {
	file_proto_ax_proto_rawDescOnce.Do(func() {
		file_proto_ax_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ax_proto_rawDesc), len(file_proto_ax_proto_rawDesc)))
	})
	return file_proto_ax_proto_rawDescData
}

var file_proto_ax_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_ax_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_ax_proto_goTypes = []any{
	(State)(0),                        // 0: ax.State
	(CancelReason)(0),                 // 1: ax.CancelReason
	(*StepEvent)(nil),                 // 2: ax.StepEvent
	(*HarnessStart)(nil),              // 3: ax.HarnessStart
	(*HarnessCancel)(nil),             // 4: ax.HarnessCancel
	(*HarnessRequest)(nil),            // 5: ax.HarnessRequest
	(*HarnessOutputs)(nil),            // 6: ax.HarnessOutputs
	(*Error)(nil),                     // 7: ax.Error
	(*HarnessEnd)(nil),                // 8: ax.HarnessEnd
	(*HarnessResponse)(nil),           // 9: ax.HarnessResponse
	(*CreateInteractionEvent)(nil),    // 10: ax.CreateInteractionEvent
	(*CreateInteractionResponse)(nil), // 11: ax.CreateInteractionResponse
	(*Step)(nil),                      // 12: ax.Step
	(*ContentStep)(nil),               // 13: ax.ContentStep
	(*ThoughtStep)(nil),               // 14: ax.ThoughtStep
	(*ToolCallStep)(nil),              // 15: ax.ToolCallStep
	(*FunctionCallStep)(nil),          // 16: ax.FunctionCallStep
	(*ToolResultStep)(nil),            // 17: ax.ToolResultStep
	(*FunctionResultStep)(nil),        // 18: ax.FunctionResultStep
	(*Value)(nil),                     // 19: ax.Value
	(*ListValue)(nil),                 // 20: ax.ListValue
	(*structpb.Struct)(nil),           // 21: google.protobuf.Struct
	(*Content)(nil),                   // 22: ax.Content
	(structpb.NullValue)(0),           // 23: google.protobuf.NullValue
}
var file_proto_ax_proto_depIdxs = []int32{
	21, // 0: ax.StepEvent.agent_config:type_name -> google.protobuf.Struct
	12, // 1: ax.StepEvent.steps:type_name -> ax.Step
	0,  // 2: ax.StepEvent.state:type_name -> ax.State
	12, // 3: ax.HarnessStart.steps:type_name -> ax.Step
	1,  // 4: ax.HarnessCancel.reason:type_name -> ax.CancelReason
	3,  // 5: ax.HarnessRequest.start:type_name -> ax.HarnessStart
	4,  // 6: ax.HarnessRequest.cancel:type_name -> ax.HarnessCancel
	12, // 7: ax.HarnessOutputs.steps:type_name -> ax.Step
	0,  // 8: ax.HarnessEnd.state:type_name -> ax.State
	7,  // 9: ax.HarnessEnd.error:type_name -> ax.Error
	6,  // 10: ax.HarnessResponse.outputs:type_name -> ax.HarnessOutputs
	8,  // 11: ax.HarnessResponse.end:type_name -> ax.HarnessEnd
	12, // 12: ax.CreateInteractionEvent.inputs:type_name -> ax.Step
	12, // 13: ax.CreateInteractionResponse.outputs:type_name -> ax.Step
	13, // 14: ax.Step.content:type_name -> ax.ContentStep
	14, // 15: ax.Step.thought:type_name -> ax.ThoughtStep
	15, // 16: ax.Step.tool_call:type_name -> ax.ToolCallStep
	17, // 17: ax.Step.tool_result:type_name -> ax.ToolResultStep
	22, // 18: ax.ContentStep.content:type_name -> ax.Content
	22, // 19: ax.ThoughtStep.summary:type_name -> ax.Content
	16, // 20: ax.ToolCallStep.function_call:type_name -> ax.FunctionCallStep
	21, // 21: ax.FunctionCallStep.arguments:type_name -> google.protobuf.Struct
	18, // 22: ax.ToolResultStep.function_result:type_name -> ax.FunctionResultStep
	19, // 23: ax.FunctionResultStep.result:type_name -> ax.Value
	23, // 24: ax.Value.null_value:type_name -> google.protobuf.NullValue
	21, // 25: ax.Value.struct_value:type_name -> google.protobuf.Struct
	20, // 26: ax.Value.list_value:type_name -> ax.ListValue
	22, // 27: ax.Value.content_value:type_name -> ax.Content
	19, // 28: ax.ListValue.values:type_name -> ax.Value
	5,  // 29: ax.HarnessService.Connect:input_type -> ax.HarnessRequest
	10, // 30: ax.InteractionsService.CreateInteraction:input_type -> ax.CreateInteractionEvent
	9,  // 31: ax.HarnessService.Connect:output_type -> ax.HarnessResponse
	11, // 32: ax.InteractionsService.CreateInteraction:output_type -> ax.CreateInteractionResponse
	31, // [31:33] is the sub-list for method output_type
	29, // [29:31] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_proto_ax_proto_init() }
func file_proto_ax_proto_init() {
	if File_proto_ax_proto != nil {
		return
	}
	file_proto_content_proto_init()
	file_proto_ax_proto_msgTypes[3].OneofWrappers = []any{
		(*HarnessRequest_Start)(nil),
		(*HarnessRequest_Cancel)(nil),
	}
	file_proto_ax_proto_msgTypes[7].OneofWrappers = []any{
		(*HarnessResponse_Outputs)(nil),
		(*HarnessResponse_End)(nil),
	}
	file_proto_ax_proto_msgTypes[10].OneofWrappers = []any{
		(*Step_Content)(nil),
		(*Step_Thought)(nil),
		(*Step_ToolCall)(nil),
		(*Step_ToolResult)(nil),
	}
	file_proto_ax_proto_msgTypes[13].OneofWrappers = []any{
		(*ToolCallStep_FunctionCall)(nil),
	}
	file_proto_ax_proto_msgTypes[15].OneofWrappers = []any{
		(*ToolResultStep_FunctionResult)(nil),
	}
	file_proto_ax_proto_msgTypes[17].OneofWrappers = []any{
		(*Value_NullValue)(nil),
		(*Value_NumberValue)(nil),
		(*Value_StringValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_StructValue)(nil),
		(*Value_ListValue)(nil),
		(*Value_ContentValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ax_proto_rawDesc), len(file_proto_ax_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_ax_proto_goTypes,
		DependencyIndexes: file_proto_ax_proto_depIdxs,
		EnumInfos:         file_proto_ax_proto_enumTypes,
		MessageInfos:      file_proto_ax_proto_msgTypes,
	}.Build()
	File_proto_ax_proto = out.File
	file_proto_ax_proto_goTypes = nil
	file_proto_ax_proto_depIdxs = nil
}
