// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/ax.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HarnessService_Connect_FullMethodName = "/ax.HarnessService/Connect"
)

// HarnessServiceClient is the client API for HarnessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HarnessServiceClient interface {
	// Connect drives one harness execution. The client sends
	// HarnessRequest{start} (and may send one HarnessRequest{cancel}
	// mid-stream), and the server streams zero or more HarnessResponse{outputs}
	// frames terminated by exactly one HarnessResponse{end}.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HarnessRequest, HarnessResponse], error)
}

type harnessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHarnessServiceClient(cc grpc.ClientConnInterface) HarnessServiceClient {
	return &harnessServiceClient{cc}
}

func (c *harnessServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HarnessRequest, HarnessResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HarnessService_ServiceDesc.Streams[0], HarnessService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HarnessRequest, HarnessResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HarnessService_ConnectClient = grpc.BidiStreamingClient[HarnessRequest, HarnessResponse]

// HarnessServiceServer is the server API for HarnessService service.
// All implementations must embed UnimplementedHarnessServiceServer
// for forward compatibility.
type HarnessServiceServer interface {
	// Connect drives one harness execution. The client sends
	// HarnessRequest{start} (and may send one HarnessRequest{cancel}
	// mid-stream), and the server streams zero or more HarnessResponse{outputs}
	// frames terminated by exactly one HarnessResponse{end}.
	Connect(grpc.BidiStreamingServer[HarnessRequest, HarnessResponse]) error
	mustEmbedUnimplementedHarnessServiceServer()
}

// UnimplementedHarnessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHarnessServiceServer struct{}

func (UnimplementedHarnessServiceServer) Connect(grpc.BidiStreamingServer[HarnessRequest, HarnessResponse]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedHarnessServiceServer) mustEmbedUnimplementedHarnessServiceServer() {}
func (UnimplementedHarnessServiceServer) testEmbeddedByValue()                        {}

// UnsafeHarnessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HarnessServiceServer will
// result in compilation errors.
type UnsafeHarnessServiceServer interface {
	mustEmbedUnimplementedHarnessServiceServer()
}

func RegisterHarnessServiceServer(s grpc.ServiceRegistrar, srv HarnessServiceServer) {
	// If the following call panics, it indicates UnimplementedHarnessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HarnessService_ServiceDesc, srv)
}

func _HarnessService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HarnessServiceServer).Connect(&grpc.GenericServerStream[HarnessRequest, HarnessResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HarnessService_ConnectServer = grpc.BidiStreamingServer[HarnessRequest, HarnessResponse]

// HarnessService_ServiceDesc is the grpc.ServiceDesc for HarnessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HarnessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ax.HarnessService",
	HandlerType: (*HarnessServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _HarnessService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/ax.proto",
}

const (
	InteractionsService_CreateInteraction_FullMethodName = "/ax.InteractionsService/CreateInteraction"
)

// InteractionsServiceClient is the client API for InteractionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InteractionsServiceClient interface {
	// CreateInteraction executes an agentic task or resumes an existing one with streaming responses
	// If the conversation_id already exists, it will be resumed.
	CreateInteraction(ctx context.Context, in *CreateInteractionEvent, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreateInteractionResponse], error)
}

type interactionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInteractionsServiceClient(cc grpc.ClientConnInterface) InteractionsServiceClient {
	return &interactionsServiceClient{cc}
}

func (c *interactionsServiceClient) CreateInteraction(ctx context.Context, in *CreateInteractionEvent, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CreateInteractionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InteractionsService_ServiceDesc.Streams[0], InteractionsService_CreateInteraction_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateInteractionEvent, CreateInteractionResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InteractionsService_CreateInteractionClient = grpc.ServerStreamingClient[CreateInteractionResponse]

// InteractionsServiceServer is the server API for InteractionsService service.
// All implementations must embed UnimplementedInteractionsServiceServer
// for forward compatibility.
type InteractionsServiceServer interface {
	// CreateInteraction executes an agentic task or resumes an existing one with streaming responses
	// If the conversation_id already exists, it will be resumed.
	CreateInteraction(*CreateInteractionEvent, grpc.ServerStreamingServer[CreateInteractionResponse]) error
	mustEmbedUnimplementedInteractionsServiceServer()
}

// UnimplementedInteractionsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInteractionsServiceServer struct{}

func (UnimplementedInteractionsServiceServer) CreateInteraction(*CreateInteractionEvent, grpc.ServerStreamingServer[CreateInteractionResponse]) error {
	return status.Error(codes.Unimplemented, "method CreateInteraction not implemented")
}
func (UnimplementedInteractionsServiceServer) mustEmbedUnimplementedInteractionsServiceServer() {}
func (UnimplementedInteractionsServiceServer) testEmbeddedByValue()                             {}

// UnsafeInteractionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InteractionsServiceServer will
// result in compilation errors.
type UnsafeInteractionsServiceServer interface {
	mustEmbedUnimplementedInteractionsServiceServer()
}

func RegisterInteractionsServiceServer(s grpc.ServiceRegistrar, srv InteractionsServiceServer) {
	// If the following call panics, it indicates UnimplementedInteractionsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InteractionsService_ServiceDesc, srv)
}

func _InteractionsService_CreateInteraction_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateInteractionEvent)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InteractionsServiceServer).CreateInteraction(m, &grpc.GenericServerStream[CreateInteractionEvent, CreateInteractionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InteractionsService_CreateInteractionServer = grpc.ServerStreamingServer[CreateInteractionResponse]

// InteractionsService_ServiceDesc is the grpc.ServiceDesc for InteractionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InteractionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ax.InteractionsService",
	HandlerType: (*InteractionsServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateInteraction",
			Handler:       _InteractionsService_CreateInteraction_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/ax.proto",
}
